# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: None

version = 1

[[annotations]]
path = ["Cargo.lock"]
SPDX-FileCopyrightText = "2026 Duszku <duszku511@gmail.com>"
SPDX-License-Identifier = "EUPL-1.2"
